site_name: VC3
site_url: https://www.docs.virtualclusters.org/
site_description: VC3 Documentation for Users and Developers
# theme_dir: 'custom_theme'
# theme: yeti
repo_url: https://github.com/vc3-project/vc3-mkdocs
# edit_url: edit/master/docs/
extra_css:
  - css/extra.css
pages:
  - Home: index.md
  - User Guide:
    - 'VC3 User Guide': 'userguide/vc3-user-guide.md'
    - 'VC3 Developers Guide': 'userguide/vc3-dev-guide.md'
  - Glossary: glossary.md
  - MK Docs Cheatsheet: mkcommands.md
markdown_extensions:
  - admonition
